/**
 * 字典文件【城市多音字】
 */
export default {
  朝阳: 'cháo,yáng',
  蔚县: 'yù,xiàn',
  单县: 'shàn,xiàn',
  莘县: 'shēn,xiàn',
  浚县: 'xùn,xiàn',
  歙县: 'shè,xiàn',
  六合: 'lù,hé',
  六安: 'lù,ān',
  大城: 'dài,chéng',
  大埔: 'dà,bù',
  乐亭: 'lào,tíng',
  乐清: 'yuè,qīng',
  绥棱: 'suí,líng',
  穆棱: 'mù,líng',
  长子: 'zhǎng,zǐ',
  洪洞: 'hóng,tóng',
  闵行: 'mǐn,háng',
  蚌埠: 'bèng,bù',
  涡阳: 'guō,yáng',
  铅山: 'yán,shān',
  东阿: 'dōng,ē',
  牟平: 'mù,píng',
  渑池: 'miǎn,chí',
  泌阳: 'bì,yáng',
  黄陂: 'huáng,pí',
  番禺: 'pān,yú',
  重庆: 'chóng,qìng',
  筠连: 'jūn,lián',
  犍为: 'qián,wéi',
  吴堡: 'wú,bǔ',
  尉犁: 'yù,lí',
  西藏: 'xī,zhàng',
  调兵山: 'diào,bīng,shān',
  延边朝鲜族: 'yán,biān,cháo,xiǎn,zú',
  长白朝鲜族: 'cháng,bái,cháo,xiǎn,zú',
};
